#!/usr/bin/env bash

# Installing load balancer

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy
apt-get update
apt-get install -y haproxy


echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg


printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
   log    global
   mode   http
   option httplog
   option dontlognull
   retries 3
   option redispatch
   timeout connect 5000
   timeout client  50000
   timeout server  50000

listen hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    http-response set-header Connection keep-alive
    server 172654-web-01 35.174.207.82:80 check
    server 172654-web-02 35.175.64.176:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
sudo systemctl enable haproxy.service

sudo systemctl restart haproxy.service
