#!/usr/bin/env bash
# Bash script that displays the visitor IP along with the HTTP status code from the Apache log file

awk '{count[$1" "$9]++} END {for (key in count) printf "\t%d %s\n", count[key], key}' apache-access.log | sort -rn
