#!/usr/bin/env bash
# Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line

i=1;
while [[ $i -le 10 ]]
do
	if [[ $i -eq 8 ]];
	then
		echo "good luck";
	elif [[ $i -eq 4 ]];
	then
		echo "bad luck";
	else
		echo "Best School";
	fi
	(( i++ ));
done
