#!/usr/bin/env bash
# configure ufw firewall to block all incoming traffic except for ports 22, 443, and 80
sudo ufw default deny incoming
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
sudo ufw enable
